#+TITLE: Emacs Configuration
#+AUTHOR: Nelson Loyola

This configuration uses the [[https://github.com/jwiegley/use-package][use-package]] package from John Wiegley,
which is a fantastic way to manage package configurations.

I've gotten ideas for this document from the following:

- [[https://github.com/danielmai/.emacs.d][Daniel Mai]]'s configuration.
- [[http://pages.sachachua.com/.emacs.d/Sacha.html][Sacha Chua site]]
- [[https://github.com/wasamasa/dotemacs/blob/master/init.org][Wasamasa]]

This file is used to generate ~config.el~ using ~org-babel~ in
~init.el~.

* Installing Emacs
** Ubuntu

I've installed Emacs from source and use the ~emacs-24.5~ tag. I used
the instructions provided by Xah Lee given [[http://ergoemacs.org/emacs/building_emacs_on_linux.html][here]], but first the
following command has to be run.

#+begin_src sh
./autogen.conf
./configure
make
sudo make install
#+end_src

*** Utility constants

#+begin_src emacs-lisp
(defconst ostype-linux
  (if (integer-or-marker-p
       (string-match "linux" system-configuration)) t nil))
#+end_src

* Personal Information

#+begin_src emacs-lisp
(setq user-full-name "Nelson Loyola"
      user-mail-address "nloyola@gmail.com")
#+end_src

* Customize settings

Set up the customize file to its own separate file, instead of saving
customize settings in [[file:init.el][init.el]].

#+begin_src emacs-lisp
(setq custom-file (expand-file-name "custom.el" user-emacs-directory))
(load custom-file)
#+end_src

* Theme
*** Monokai theme

#+begin_src emacs-lisp
(use-package monokai-theme
  :ensure t
  :init
  (progn
    (load-theme 'monokai t)
    (setq frame-background-mode `dark)
    (setq monokai-use-variable-pitch nil)))
#+end_src

* Font

[[http://input.fontbureau.com/download/][Input Font]]: Install it on Ubuntu as follows:

#+begin_src sh :tangle no
mv Input-Font.zip ~/.fonts
cd ~/.fonts
unzip Input-Font.zip
#+end_src

And here's how we tell Emacs how to use a font. Copy the following line to your
=~/.Xresources= file.

#+begin_src sh :tangle no
Emacs.font: Input Mono Condensed-9
#+end_src

And then merge the setting to your X server resource database.

#+begin_src sh :tangle no
xrdb -merge ~/.Xresources
#+end_src
* Sane defaults
** General

Some commands are disabled by default. They are enabled in our config
using the following:

#+begin_src emacs-lisp
(put 'downcase-region 'disabled nil)
(put 'upcase-region 'disabled nil)
(put 'narrow-to-region 'disabled nil)
(put 'dired-find-alternate-file 'disabled nil)
#+end_src

Sentences end with a single space.

#+BEGIN_SRC emacs-lisp
(setq sentence-end-double-space nil)
#+END_SRC

Set the default major mode to ~text-mode~. By default it's fundamental mode which is
not what we want. Also, use ~text-mode~ for the scratch buffer.

#+BEGIN_SRC emacs-lisp
(setq default-major-mode 'text-mode
      initial-major-mode 'text-mode)
#+END_SRC

Don't make any backup files.

#+BEGIN_SRC emacs-lisp
(setq make-backup-files nil)
#+END_SRC

Don't add new lines past end of file.

#+BEGIN_SRC emacs-lisp
(setq next-line-add-newlines nil)
#+END_SRC

Don't scroll to middle of page. Also, scroll line by line, without
scrolloff and try to keep point at the same visual place when
scrolling by page.

#+BEGIN_SRC emacs-lisp
(setq scroll-step 1
      scroll-conservatively 10000
      scroll-preserve-screen-position t)
#+END_SRC

Don't want an audible bell.

#+BEGIN_SRC emacs-lisp
(setq visible-bell t)
#+END_SRC

Add \n to end of file if required.

#+BEGIN_SRC emacs-lisp
(setq require-final-newline t)
#+END_SRC

Level of decoration {1 - 3}, t = max.

#+BEGIN_SRC emacs-lisp
(setq font-lock-maximum-decoration t)
#+END_SRC

For symlinks, automatically follow the link and visits the real file instead.

#+BEGIN_SRC emacs-lisp
(setq vc-follow-symlinks nil)
#+END_SRC

Make searches case insensitive.

#+BEGIN_SRC emacs-lisp
(setq-default case-fold-search t)
#+END_SRC

Use spaces instead of ~\t~ character.

#+BEGIN_SRC emacs-lisp
(setq-default indent-tabs-mode nil)
#+END_SRC

Turn off auto-save.

#+BEGIN_SRC emacs-lisp
(setq auto-save-default nil)
#+END_SRC

Autosave files are created between saves after a sufficient timeout in
the current directory for crash detection, they begin and end with
=#=.  Change this location to the emacs directory.

#+BEGIN_SRC emacs-lisp
(setq auto-save-list-file-prefix "~/.emacs.d/autosave/")
(setq auto-save-file-name-transforms '((".*" "~/.emacs.d/autosave/" t)))
#+END_SRC



Set line wrap at column 100.

#+BEGIN_SRC emacs-lisp
(setq fill-column 100)
#+END_SRC

Replace "yes or no" prompt with "y or n" prompt.

#+BEGIN_SRC emacs-lisp
(fset 'yes-or-no-p 'y-or-n-p)
#+END_SRC

Use UTF-8 everywhere.

#+BEGIN_SRC emacs-lisp
(setq locale-coding-system 'utf-8)
(set-terminal-coding-system 'utf-8)
(set-keyboard-coding-system 'utf-8)
(set-selection-coding-system 'utf-8)
(prefer-coding-system 'utf-8)
#+END_SRC

Use spaces instead of tabs.

#+BEGIN_SRC emacs-lisp
(setq-default indent-tabs-mode nil)
#+END_SRC

Turn off the blinking cursor.

#+BEGIN_SRC emacs-lisp
(blink-cursor-mode -1)
#+END_SRC

Indicate unused lines at the end of the window with a small image in
the left fringe.

#+BEGIN_SRC emacs-lisp
(setq-default indicate-empty-lines t)
#+END_SRC

Delete the region when typing, just like as we expect nowadays.

#+BEGIN_SRC emacs-lisp
(delete-selection-mode t)
#+END_SRC

Highlight matching delimiters.

#+BEGIN_SRC emacs-lisp
(show-paren-mode t)
#+END_SRC

Display the column number in the mode line.

#+BEGIN_SRC emacs-lisp
(column-number-mode t)
#+END_SRC

Use the directory name to make buffer names unique.

#+BEGIN_SRC emacs-lisp
(setq uniquify-buffer-name-style 'forward)
#+END_SRC

Window management. ~C-c left (winner-undo)~ undoes the last window
configuration change. Redo the changes using ~C-c right
(winner-redo)~. Also move from window to window using Meta and the
direction keys.

#+BEGIN_SRC emacs-lisp
(winner-mode 1)
#+END_SRC

Highlight matches in query-replace mode.

#+BEGIN_SRC emacs-lisp
(setq query-replace-highlight t)
#+END_SRC

Use visual line mode to display long lines.

#+BEGIN_SRC emacs-lisp
(global-visual-line-mode -1)
#+END_SRC

Replace the standard text representation of various identifiers/symbols
with a (arguably) more aesthetically pleasing representation.

#+BEGIN_SRC emacs-lisp
(global-prettify-symbols-mode +1)
#+END_SRC

Frame title.

#+BEGIN_SRC emacs-lisp
(setq frame-title-format
      '("" invocation-name ": " (:eval (replace-regexp-in-string
                                        "^ +" "" (buffer-name)))))
#+END_SRC

Make completion buffers disappear after 10 seconds.

#+BEGIN_SRC emacs-lisp
(add-hook 'completion-setup-hook
          (lambda () (run-at-time 10 nil
                                  (lambda () (delete-windows-on "*Completions*")))))
#+END_SRC

Get rid of the menu bar.

#+BEGIN_SRC emacs-lisp
(if (fboundp 'menu-bar-mode) (menu-bar-mode -1))
#+END_SRC

Do not ask me to save files before compiling.

#+BEGIN_SRC emacs-lisp
(setq compilation-ask-about-save nil)
#+END_SRC

Revert these files without asking.

#+BEGIN_SRC emacs-lisp
(setq revert-without-query '(".*"))
#+END_SRC

Default command when using ~grep~.

#+BEGIN_SRC emacs-lisp
(setq grep-command "grep -nH -r --include=\\* -e  .")
#+END_SRC

Middle-clicking is nice to paste, however it should not adjust point
and paste at the then adjusted point.

#+BEGIN_SRC emacs-lisp
(setq mouse-yank-at-point t)
#+END_SRC

Do not show thees modes in the mode line.

#+begin_src emacs-lisp
(diminish 'visual-line-mode)
(diminish 'abbrev-mode)
#+end_src

Save clipboard data of other programs in the kill ring when possible.

#+BEGIN_SRC emacs-lisp
(setq save-interprogram-paste-before-kill t)
#+END_SRC

Don't use dialog boxes

#+BEGIN_SRC emacs-lisp
(setq use-dialog-box nil)
#+END_SRC

* Emacs client

#+begin_src emacs-lisp
(use-package edit-server
  :if window-system
  :init
  (add-hook 'after-init-hook 'server-start t)
  (add-hook 'after-init-hook 'edit-server-start t))
#+end_src

* Occur

The following function for ~occur-dwim~ is taken from [[https://github.com/abo-abo][Oleh Krehel]] from
[[http://oremacs.com/2015/01/26/occur-dwim/][his blog post at (or emacs]]. It takes the current region or the symbol
at point as the default value for occur.

#+begin_src emacs-lisp
(defun occur-dwim ()
  "Call `occur' with a sane default."
  (interactive)
  (push (if (region-active-p)
            (buffer-substring-no-properties
             (region-beginning)
             (region-end))
          (thing-at-point 'symbol))
        regexp-history)
  (call-interactively 'occur))
#+end_src
* Key bindings

#+begin_src emacs-lisp
(global-set-key (kbd "M-g g")         'goto-line)
(global-set-key (kbd "M-%")           'query-replace-regexp)
;;(global-set-key "\C-x\C-e"          'compile)
(global-set-key (kbd "C-x C-n")       'next-error)
(global-set-key (kbd "C-x C-i")       'c-indent-exp)

(global-set-key (kbd "<f1>")          'indent-for-tab-command)
(global-set-key [(shift f1)]          'indent-region)
(global-set-key (kbd "<f2>")          '(lambda () (interactive) (save-some-buffers t)))
(global-set-key [(shift f2)]          '(lambda () (interactive) (revert-buffer t t)))
(global-set-key [(shift f3)]          'helm-recentf)
(global-set-key [(meta shift f3)]     'sbt-grep)
(global-set-key [f4]                  'next-error)
(global-set-key [f5]                  'compile)
(global-set-key [(shift f5)]          'toggle-truncate-lines)
(global-set-key [(shift f11)]         'eval-region)
(global-set-key [(control shift f11)] 'align-regexp)
#+end_src

* List buffers

ibuffer is the improved version of list-buffers.

#+begin_src emacs-lisp
(defalias 'list-buffers 'ibuffer)
#+end_src


source: http://ergoemacs.org/emacs/emacs_buffer_management.html

#+begin_src emacs-lisp
(add-hook 'dired-mode-hook 'auto-revert-mode)

;; Also auto refresh dired, but be quiet about it
(setq global-auto-revert-non-file-buffers t)
(setq auto-revert-verbose nil)
#+end_src

source: [[http://whattheemacsd.com/sane-defaults.el-01.html][Magnars Sveen]]

** Transpose frame

#+begin_src emacs-lisp
(use-package transpose-frame
  :ensure t
  :bind ("S-M-t" . transpose-frame))
#+end_src
* Whitespace mode

#+begin_src emacs-lisp
(use-package whitespace
  :bind ("S-<f10>" . whitespace-mode))
#+end_src

* Packages bundled with Emacs

*** =bookmark=

Prefer saving this file somewhere other than the default.

#+BEGIN_SRC emacs-lisp
(setq bookmark-default-file "~/.emacs.d/etc/bookmarks")
#+END_SRC

*** =dired=
#+BEGIN_SRC emacs-lisp
(setq dired-listing-switches "-aBhl  --group-directories-first")
#+END_SRC
*** =ediff=
#+BEGIN_SRC emacs-lisp
(setq ediff-split-window-function 'split-window-horizontally
      ediff-window-setup-function 'ediff-setup-windows-plain
      ediff-diff-options "-bw")
#+END_SRC

*** =org-mode=

First some UI and editing tweaks.

#+BEGIN_SRC emacs-lisp
(setq org-catch-invisible-edits 'error
      org-startup-indented t
      org-cycle-include-plain-lists 'integrate
      org-ellipsis " […]"
      org-return-follows-link t
      org-M-RET-may-split-line nil
      org-src-fontify-natively t
      org-src-preserve-indentation t
      org-enforce-todo-dependencies t
      org-enforce-todo-checkbox-dependencies t
      org-link-frame-setup '((file . find-file)))
#+END_SRC

**** Org activation bindings

Set up some global key bindings that integrate with Org Mode features.

#+begin_src emacs-lisp
(bind-key "C-c l" 'org-store-link)
(bind-key "C-c c" 'org-capture)
(bind-key "C-c a" 'org-agenda)
#+end_src

***** Org agenda

Learned about [[https://github.com/sachac/.emacs.d/blob/83d21e473368adb1f63e582a6595450fcd0e787c/Sacha.org#org-agenda][this =delq= and =mapcar= trick from Sacha Chua's config]].

#+begin_src emacs-lisp
(setq org-agenda-files
      (delq nil
            (mapcar (lambda (x) (and (file-exists-p x) x))
                    '("~/Dropbox/Agenda"))))
#+end_src

***** Org capture

#+begin_src emacs-lisp
(bind-key "C-c c" 'org-capture)
(setq org-default-notes-file "~/Dropbox/Notes/notes.org")
#+end_src

**** Org setup

Speed commands are a nice and quick way to perform certain actions
while at the beginning of a heading. It's not activated by default.

See the doc for speed keys by checking out [[elisp:(info%20"(org)%20speed%20keys")][the documentation for
speed keys in Org mode]].

#+begin_src emacs-lisp
(setq org-use-speed-commands t)
#+end_src

#+begin_src emacs-lisp
(setq org-image-actual-width 550)
#+end_src

**** Org tags

The default value is -77, which is weird for smaller width windows.
I'd rather have the tags align horizontally with the header. 45 is a
good column number to do that.

#+begin_src emacs-lisp
(setq org-tags-column 45)
#+end_src

**** Org babel languages

#+begin_src emacs-lisp
(org-babel-do-load-languages
 'org-babel-load-languages
 '((python . t)
   (C . t)
   (calc . t)
   (latex . t)
   (java . t)
   (ruby . t)
   (scheme . t)
   (sh . t)
   (sqlite . t)
   (js . t)))

(defun my-org-confirm-babel-evaluate (lang body)
  "Do not confirm evaluation for these languages."
  (not (or (string= lang "C")
           (string= lang "java")
           (string= lang "python")
           (string= lang "emacs-lisp")
           (string= lang "sqlite"))))
(setq org-confirm-babel-evaluate 'my-org-confirm-babel-evaluate)
#+end_src

**** Org babel/source blocks

Have source blocks properly syntax highlighted and with the editing popup window staying within the
same window so all the windows don't jump around. Also, having the top and bottom trailing lines in
the block is a waste of space, so we can remove them.

Fontification doesn't work with markdown mode when the block is indented after editing it in the org
src buffer---the leading #s for headers don't get fontified properly because they appear as Org
comments.

#+begin_src emacs-lisp
(setq org-src-window-setup 'current-window
      org-src-strip-leading-and-trailing-blank-lines t
      org-src-tab-acts-natively t)
#+end_src

*** =re-builder=

Interactive preview for RE construction.

It's important to note that there's three flavours of regular
expressions encountered in Emacs.  The =read= syntax is most
reminiscent of other RE dialects, but only used in prompts.  The
=string= syntax is used in code doubles the amount of backslashes as
the RE strings are passed through the reader which removes the
extraneous ones.  Finally, there's the ~rx~ macro one can use for
writing lispy RE.

All listed RE syntaxes are supported by =re-builder=.  For whatever
reason though the =read= syntax is default (which doesn't make much
sense for me since Evil gives me search/replace preview), I prefer
having the =string= syntax as default.

#+BEGIN_SRC emacs-lisp
(setq reb-re-syntax 'string)
#+END_SRC

*** =recentf=

#+begin_src emacs-lisp
(use-package recentf
  :commands ido-recentf-open
  :init
  (progn
    (recentf-mode t)
    (setq recentf-save-file "~/.emacs.d/etc/recentf"
          recentf-max-saved-items 50)))
#+end_src

*** =savehist=

The history of prompts like =M-:= can be saved, but let's change its
save file and history length first.

#+BEGIN_SRC emacs-lisp
(setq savehist-file "~/.emacs.d/etc/savehist"
      history-length 150)
#+END_SRC

*** =save-place=

Remember position in a file.

#+BEGIN_SRC emacs-lisp
(setq-default save-place t)
(setq save-place-file "~/.emacs.d/etc/saveplace")
#+END_SRC
*** =shell=

#+begin_src emacs-lisp
(bind-key "C-x m" 'shell)
(bind-key "C-x M" 'ansi-term)
#+end_src

*** =tramp=
#+begin_src emacs-lisp :tangle no
(use-package tramp)
#+end_src
*** =windmove=

=windmove= provides useful commands for moving window focus by
direction, I prefer having wraparound instead of getting errors
though.

#+BEGIN_SRC emacs-lisp
(windmove-default-keybindings 'meta)
(setq windmove-wrap-around t)
#+END_SRC
*** =winner-mode=

Winner mode allows you to undo/redo changes to window changes in Emacs
and allows you.

#+begin_src emacs-lisp
(winner-mode t)
#+end_src

** line numbers.

#+begin_src emacs-lisp
(dolist (mode-hook '(text-mode-hook prog-mode-hook))
  (add-hook mode-hook
            (lambda ()
              (linum-mode 1))))
#+end_src

** Text mode

#+begin_src emacs-lisp
(setq text-mode-hook
      '(lambda ()
         (turn-on-auto-fill)            ; Enable automatic line wrapping.
         (setq-default indent-tabs-mode nil)))    ; Use real tabs.
#+end_src

** Shell

#+begin_src emacs-lisp
(defvar my-term-shell "/bin/zsh")
(defadvice ansi-term (before force-bash)
  (interactive (list my-term-shell)))
(ad-activate 'ansi-term)

(defun my-term-use-utf8 ()
  (set-buffer-process-coding-system 'utf-8-unix 'utf-8-unix))
(add-hook 'term-exec-hook 'my-term-use-utf8)

(defun my-term-paste (&optional string)
  (interactive)
  (process-send-string
   (get-buffer-process (current-buffer))
   (if string string (current-kill 0))))

(defun my-term-hook ()
  (goto-address-mode)
  (define-key term-raw-map "\C-y" 'my-term-paste)
  (let ((base03  "#002b36")
        (base02  "#073642")
        (base01  "#586e75")
        (base00  "#657b83")
        (base0   "#839496")
        (base1   "#93a1a1")
        (base2   "#eee8d5")
        (base3   "#fdf6e3")
        (yellow  "#b58900")
        (orange  "#cb4b16")
        (red     "#dc322f")
        (magenta "#d33682")
        (violet  "#6c71c4")
        (blue    "#268bd2")
        (cyan    "#2aa198")
        (green   "#859900"))
    (setq ansi-term-color-vector
          (vconcat `(unspecified ,base02 ,red ,green ,yellow ,blue
                                 ,magenta ,cyan ,base2)))
    (my-term-use-utf8)
    ))

(add-hook 'term-exec-hook 'my-term-hook)
#+end_src

** Remove trailing whitespace
#+BEGIN_SRC emacs-lisp
(add-hook 'before-save-hook 'delete-trailing-whitespace)
#+END_SRC

* ELPA packages

These are the packages that are not built into Emacs.

** [[https://github.com/abo-abo/ace-window][ace-window]]

A package that uses the same idea from ace-jump-mode for
buffer navigation, but applies it to windows. The default keys are
1-9, but it's faster to access the keys on the home row, so that's
what I have them set to (with respect to Dvorak, of course).

#+begin_src emacs-lisp
(use-package ace-window)
#+end_src

** [[https://github.com/abo-abo/avy][avy]]

A quick way to jump around text in buffers.

#+begin_src emacs-lisp
  (use-package avy
               :bind (("C-c SPC" . avy-goto-char)
                      ("C-'" . avy-goto-char-2)
                      ("M-g M-g" . avy-goto-line)))
#+end_src

** [[https://github.com/jorgenschaefer/circe][Circe]]

#+BEGIN_SRC emacs-lisp
(use-package circe
  :ensure t
  :config (setq circe-default-nick "chucho"
                circe-default-user "chucho"
                circe-default-realname "chucho"
                circe-default-part-message "Bye"
                circe-default-quit-message "Bye"
                circe-network-options '(("Freenode"
                                         :tls t
                                         :channels ("#emacs")
                                         ))))
#+END_SRC

** [[https://github.com/ankurdave/color-identifiers-mode][color-identifiers]]

Color Identifiers is a minor mode for Emacs that highlights each source code identifier uniquely
based on its name.

#+begin_src emacs-lisp
(use-package color-identifiers-mode
  :ensure t
  :diminish color-identifiers-mode
  :config
  (progn
    (add-hook 'after-init-hook 'global-color-identifiers-mode)))
#+end_src

** [[https://github.com/company-mode/company-mode][company-mode]]

Complete anything.

#+begin_src emacs-lisp
(use-package company
  :ensure t
  :diminish company-mode
  :config
  (progn
    (add-hook 'after-init-hook 'global-company-mode)
    (global-set-key (kbd "M-/") 'company-complete-common)
    (use-package company-tern)
    ))
#+end_src

** [[https://github.com/senny/emacs-eclim][emacs-eclim]]

Provides Emacs with some Eclipse features for Java development. Eclim has to be installed first and
can be downloaded from [[http://eclim.org/install.html][here]].

#+begin_src emacs-lisp
(use-package eclim
  :ensure emacs-eclim
  :diminish eclim-mode
  :init (use-package cl)
  :config
  (progn
    (global-eclim-mode)
    (use-package eclimd)
    (use-package company)
    (use-package company-emacs-eclim)
    (company-emacs-eclim-setup)
    (global-company-mode t)
    (add-hook 'java-mode-hook (lambda() (eclim-mode t)))
    (setq eclim-auto-save t
          eclimd-wait-for-process nil
          eclimd-default-workspace "~/workspace/"
          help-at-pt-display-when-idle t
          help-at-pt-timer-delay 0.1)
    ;; Call the help framework with the settings above & activate eclim-mode
    (help-at-pt-set-timer)

    ;; keep consistent which other auto-complete backend.
    (custom-set-faces
     '(ac-emacs-eclim-candidate-face ((t (:inherit ac-candidate-face))))
     '(ac-emacs-eclim-selection-face ((t (:inherit ac-selection-face)))))
    )
  )
#+end_src

** [[https://github.com/magnars/expand-region.el][expand-region]]

#+begin_src emacs-lisp
(use-package expand-region
  :ensure t
  :bind ("C-=" . er/expand-region))
#+end_src

** [[http://www.emacswiki.org/emacs/fic-mode.el][fic-mode]]

Show FIXME/TODO/BUG/KLUDGE in special face only in comments and
strings.

#+BEGIN_SRC emacs-lisp
(use-package fic-mode
  :ensure t
  :config
  (progn
    (add-hook 'c++-mode-hook 'turn-on-fic-mode)
    (add-hook 'c-mode-hook 'turn-on-fic-mode)
    (add-hook 'java-mode-hook 'turn-on-fic-mode)
    (add-hook 'vala-mode-hook 'turn-on-fic-mode)
    (add-hook 'python-mode-hook 'turn-on-fic-mode)
    ))
#+END_SRC

** [[http://www.emacswiki.org/emacs/framemove.el][framemove]]

Allow windmove to jump between frames.

#+BEGIN_SRC emacs-lisp
(use-package framemove
  :ensure t
  :config (setq framemove-hook-into-windmove t)
  )
#+END_SRC

** [[https://github.com/flycheck/flycheck][flycheck]]

#+begin_src emacs-lisp
(use-package flycheck
  :ensure t
  :diminish flycheck-mode
  :config
  (progn
    (add-hook 'after-init-hook #'global-flycheck-mode)
    (setq flycheck-standard-error-navigation nil)
    (use-package flycheck-protobuf
      :config
      (progn
        (add-to-list 'flycheck-checkers 'protobuf-protoc-reporter t)
        )
      )))
#+end_src

** [[https://github.com/leoliu/ggtags][ggtags]]Generate tags on command line with ~gtags~.
Updte tags on command line with ~global -u~.

#+BEGIN_SRC emacs-lisp
(use-package ggtags
  :ensure t
  :commands ggtags-mode)
#+END_SRC
** [[https://github.com/jacobono/emacs-gradle-mode][emacs-gradle-mode]]

#+BEGIN_SRC emacs-lisp
(use-package gradle-mode
  :ensure t
  :diminish gradle-mode
  :init
  (progn
    (gradle-mode 1)))
#+END_SRC

** [[https://github.com/camdez/goto-last-change.el][goto-last-change]]

#+begin_src emacs-lisp
      (use-package goto-last-change
        :ensure t
        :config
        (progn
          (autoload 'goto-last-change "goto-last-change"
            "Set point to the position of the last change." t)

          (global-set-key "\C-x\C-\\" 'goto-last-change)
          ))
#+end_src

** [[https://github.com/Groovy-Emacs-Modes/groovy-emacs-modes][groovy-mode]]

Required for gradle build files.

#+BEGIN_SRC emacs-lisp
  (use-package groovy-mode
               :ensure t)
#+END_SRC

** [[https://github.com/kai2nenobu/guide-key][guide-key]]

Guide the following key bindings automatically and dynamically.

#+BEGIN_SRC emacs-lisp
(use-package guide-key
  :ensure t
  :diminish guide-key-mode
  :config
  (progn
    (setq guide-key/guide-key-sequence '("C-x r" "C-c p" "C-h"))
    (guide-key-mode 1)
  ))
#+END_SRC

** [[https://github.com/emacs-helm/helm][helm]]

GNU Global and projectile: use ~C-c p R~ to regenerate tag file.

#+begin_src emacs-lisp
(use-package helm
  :ensure t
  :diminish helm-mode
  :init (progn
          ;; must set before helm-config, otherwise helm uses the default
          ;; prefix "C-x c", which is inconvenient because you can
          ;; accidentially press "C-x C-c"
          (setq helm-command-prefix-key "C-c h")
          (require 'helm-config)
          (require 'helm-eshell)
          (require 'helm-files)
          (require 'helm-grep)
          (use-package helm-projectile
            :ensure t
            :commands helm-projectile
            :bind (("C-c p h" . helm-projectile))
            :config
            (progn
              (setq projectile-remember-window-configs t
                    projectile-switch-project-action 'projectile-dired
                    projectile-completion-system 'default
                    projectile-enable-caching nil
                    compilation-read-command nil ; do not prompt for a compilation command
                    )

              (projectile-global-mode)
              (setq projectile-completion-system 'helm)
              ))
          (require 'helm-projectile)
          (use-package helm-ag :ensure t :commands helm-ag)
          (use-package helm-c-yasnippet
            :ensure t
            :init (use-package yasnippet)
            :config (global-set-key (kbd "C-c y") 'helm-yas-complete))
          (use-package helm-flx :ensure t :commands helm-flx-mode)
          (use-package helm-gtags
            :ensure t
            :commands helm-gtags-mode
            :bind (("M-." . helm-gtags-find-tag)
                   ("M-," . helm-gtags-find-rtag)))
          (use-package helm-swoop :ensure t)

          (helm-projectile-on)
          (helm-flx-mode +1)
          ;; rebihnd tab to do persistent action
          (define-key helm-map (kbd "<tab>") 'helm-execute-persistent-action)
          ;; make TAB works in terminal
          (define-key helm-map (kbd "C-i") 'helm-execute-persistent-action)
          ;; list actions using C-z
          (define-key helm-map (kbd "C-z")  'helm-select-action)

          (with-eval-after-load 'helm-files
            (define-key helm-grep-mode-map (kbd "<return>")  'helm-grep-mode-jump-other-window)
            (define-key helm-grep-mode-map (kbd "n")  'helm-grep-mode-jump-other-window-forward)
            (define-key helm-grep-mode-map (kbd "p")  'helm-grep-mode-jump-other-window-backward))

          (setq helm-ff-newfile-prompt-p nil
                helm-M-x-fuzzy-match t
                helm-google-suggest-use-curl-p t
                ;; scroll 4 lines other window using M-<next>/M-<prior>
                helm-scroll-amount 4
                ;; do not display invisible candidates
                helm-quick-update t
                ;; be idle for this many seconds, before updating in delayed sources.
                helm-idle-delay 0.01
                ;; be idle for this many seconds, before updating candidate buffer
                helm-input-idle-delay 0.01
                ;; search for library in `require` and `declare-function` sexp.
                helm-ff-search-library-in-sexp t

                helm-split-window-default-side 'below
                helm-split-window-in-side-p nil
                helm-always-two-windows nil
                helm-buffers-favorite-modes (append helm-buffers-favorite-modes
                                                    '(picture-mode artist-mode))
                ;; limit the number of displayed canidates
                helm-candidate-number-limit 100
                ;; show all candidates when set to 0
                helm-M-x-requires-pattern 0
                helm-ff-file-name-history-use-recentf t
                ;; move to end or beginning of source when reaching top or bottom of source.
                helm-move-to-line-cycle-in-source t
                ;; Needed in helm-buffers-list
                ido-use-virtual-buffers t
                ;; fuzzy matching buffer names when non--nil, useful in helm-mini that lists buffers
                helm-buffers-fuzzy-matching t
                ;; truncate long lines
                helm-truncate-lines t
                helm-autoresize-min-height 15
                helm-autoresize-max-height 15
                helm-display-header-line nil
                helm-buffer-max-length 45
                helm-yas-display-key-on-candidate t)

          ;; helm windows shows at the bottom
          ;;
          ;; from http://www.reddit.com/r/emacs/comments/345vtl/make_helm_window_at_the_bottom_without_using_any/
          ;;
          ;; see also http://www.lunaryorn.com/2015/04/29/the-power-of-display-buffer-alist.html
          ;; (cond (window-system
          ;;        (add-to-list 'display-buffer-alist
          ;;                     `("\\*helm"
          ;;                       (display-buffer-in-side-window)
          ;;                       (inhibit-same-window . nil)
          ;;                       (reusable-frames . visible)
          ;;                       (side            . bottom)
          ;;                       (window-height   . 0.15)))
          ;;        ))
          ;; Save current position to mark ring when jumping to a different place
          (add-hook 'helm-goto-line-before-hook 'helm-save-current-pos-to-mark-ring)
          (helm-mode)
          (helm-autoresize-mode 1))
  :bind (("M-x" . helm-M-x)
         ("M-y" . helm-show-kill-ring)
         ("C-x b" . helm-mini)
         ("C-x C-f" . helm-find-files)
         ("C-c h" . helm-command-prefix)
         ("C-`" . helm-resume)))
#+end_src

*** Search

[[http://www.gnu.org/software/grep/][grep]] is very fast, but not the best tool for code search, especially
not within compressed files. That's why I'll go for [[https://github.com/ggreer/the_silver_searcher/][ag]] instead, its
=-z= option enables the usage of the very great [[http://libarchive.org/][libarchive]]. For =helm=
to recognize the matches properly I need to enable line numbers and
columns in its output, something the =--vimgrep== option (the irony)
does. Another subtle hack hidden in here is deliberately using the
recursing variant for both types of searches, this might break
something, but so far hasn't shown any obvious side-effects

#+BEGIN_SRC emacs-lisp
(setq helm-grep-default-command "ag --vimgrep -z %p %f"
      helm-grep-default-recurse-command "ag --vimgrep -z %p %f")
#+END_SRC
**** Other

Highlighting of token matches is a tad slow, let's speed it up.

#+BEGIN_SRC emacs-lisp
(setq helm-mp-highlight-delay 0.3)
#+END_SRC

I don't know why, but helm tries doing window management.  Please
stop:

#+BEGIN_SRC emacs-lisp
(setq helm-display-function 'pop-to-buffer)
#+END_SRC

** [[https://github.com/boyw165/hl-anything][hl-anything]]

Not used for now since it breaks ERC font lock.

#+BEGIN_SRC emacs-lisp :tangle no
(use-package hl-anything
  :ensure t
  :config
  (progn
    (hl-highlight-mode 1)
    ;; (hl-setup-default-advices nil)
    ;; (hl-setup-customizable-advices nil)
    ;; (remove-hook 'kill-emacs-hook 'hl-save-highlights)
    ))
#+END_SRC

** [[https://github.com/nflath/hungry-delete][hungry-delete]]

So that hungry deletion can be used in all modes.

#+begin_src emacs-lisp
  (use-package hungry-delete
               :ensure t
               :config
               (progn
                 (global-hungry-delete-mode)
                 ))
#+end_src

** [[https://github.com/abo-abo/hydra][hydra]]

This package can be used to tie related commands into a family of
short bindings with a common prefix - a Hydra.

#+begin_src emacs-lisp
(use-package hydra
  :ensure t
  :init
  (progn
    (use-package cl-lib)
    (use-package lv)
    (use-package ace-window :ensure t)
    (use-package avy :ensure t)
    (use-package key-chord
      :ensure t
      :config (key-chord-mode 1))
    )
  :config
  (progn
    ;; http://oremacs.com/2015/01/29/more-hydra-goodness/

    (defun hydra-universal-argument (arg)
      (interactive "P")
      (setq prefix-arg (if (consp arg)
                           (list (* 4 (car arg)))
                         (if (eq arg '-)
                             (list -4)
                           '(4)))))

    (defhydra hydra-window (global-map "C-M-o")
      "window"
      ("h" windmove-left "left")
      ("j" windmove-down "down")
      ("k" windmove-up "up")
      ("l" windmove-right "right")
      ("a" ace-window "ace")
      ("u" hydra-universal-argument "universal")
      ("s" (lambda nil (interactive) (ace-window 4)) "swap")
      ("d" (lambda nil (interactive) (ace-window 16)) "delete"))

    (key-chord-define-global "yy" 'hydra-window/body)

    ;;
    ;; Taken from http://doc.rix.si/org/fsem.html
    ;;
    (defhydra hydra-zoom (global-map "C-c z")
      "zoom"
      ("g" text-scale-increase "in")
      ("l" text-scale-decrease "out"))
    )

  (defhydra hydra-eclim (:color teal
                                :hint nil)
    "
Eclim:
 ╭─────────────────────────────────────────────────────┐
 │ Java                                                │       Problems
╭┴─────────────────────────────────────────────────────┴────────────────────────────────────╯
  _d_: Show Doc             _i_: Implement (Override)          _p_: Show Problems
  _g_: Make getter/setter  _fd_: Find Declarations             _c_: Show Corrections
  _o_: Organize Imports    _fr_: Find References               _r_: Buffer Refresh
  _h_: Hierarchy            _R_: Refactor
  _s_: Semantic
Project
──────────────────
_j_: Jump to proj
_b_: Create
_k_: Import Proj
_u_: Update
"
    ("d"   eclim-java-show-documentation-for-current-element)
    ("g"   eclim-java-generate-getter-and-setter)
    ("o"   eclim-java-import-organize)
    ("h"   eclim-java-call-hierarchy)
    ("s"   helm-semantic)
    ("i"   eclim-java-implement)
    ("fd"  eclim-java-find-declaration)
    ("fr"  eclim-java-find-references)
    ("R"   eclim-java-refactor-rename-symbol-at-point)
    ("p"   eclim-problems)
    ("c"   eclim-problems-correct)
    ("r"   eclim-problems-buffer-refresh)
    ("j"   eclim-project-goto)
    ("b"   eclim-project-create)
    ("k"   eclim-project-import)
    ("u"   (lambda () (interactive) (eclim-project-update (eclim-project-name))))
    ("q"   nil "cancel" :color blue))

  (define-key eclim-mode-map (kbd "C-c e") 'hydra-eclim/body))
#+end_src

** [[https://github.com/joddie/macrostep][macrostep]]

Macrostep allows you to see what Elisp macros expand to. Learned about
it from the [[https://www.youtube.com/watch?v%3D2TSKxxYEbII][package highlight talk for use-package]].

#+begin_src emacs-lisp
(use-package macrostep
  :ensure t)
#+end_src

** [[https://github.com/magit/magit][magit]]

A great interface for git projects. It's much more pleasant to use than the git interface on the
command line. Use an easy keybinding to access magit.

#+begin_src emacs-lisp
  (use-package magit
    :ensure t
    :config
    (progn
     (define-key magit-status-mode-map (kbd "q") 'magit-quit-session)
     (setq magit-push-always-verify nil)
     ))
#+end_src

*** Fullscreen magit

#+BEGIN_QUOTE
The following code makes magit-status run alone in the frame, and then restores the old window
configuration when you quit out of magit.

No more juggling windows after commiting. It's magit bliss.
#+END_QUOTE
[[http://whattheemacsd.com/setup-magit.el-01.html][Source: Magnar Sveen]]

#+begin_src emacs-lisp
;; full screen magit-status
(defadvice magit-status (around magit-fullscreen activate)
  (window-configuration-to-register :magit-fullscreen)
  ad-do-it
  (delete-other-windows))

(defun magit-quit-session ()
  "Restores the previous window configuration and kills the magit buffer"
  (interactive)
  (kill-buffer)
  (jump-to-register :magit-fullscreen))
#+end_src

** [[https://github.com/defunkt/markdown-mode][markdown-mode]]

#+begin_src emacs-lisp
(use-package markdown-mode
  :ensure t
  :mode (("\\.markdown\\'" . markdown-mode)
         ("\\.md\\'"       . markdown-mode)))
#+end_src

** [[https://github.com/magnars/multiple-cursors.el][multiple-cursors]]

We'll also need to ~(require 'multiple-cusors)~ because of [[https://github.com/magnars/multiple-cursors.el/issues/105][an autoload issue]].

#+begin_src emacs-lisp
(use-package multiple-cursors
  :ensure t
  :init (require 'multiple-cursors)
  :bind (("C-S-c C-S-c" . mc/edit-lines)
         ("C->"         . mc/mark-next-like-this)
         ("C-<"         . mc/mark-previous-like-this)
         ("C-c C-<"     . mc/mark-all-like-this)
         ("C-!"         . mc/mark-next-symbol-like-this)
         ("s-d"         . mc/mark-all-dwim)))
#+end_src

** [[https://github.com/nex3/perspective-el][perspective]]

This package provides tagged workspaces.

#+begin_src emacs-lisp :tangle no
(use-package perspective
  :ensure t
  :config (persp-mode))
#+end_src

** [[https://github.com/bbatsov/projectile][projectile]]

#+BEGIN_QUOTE
Project navigation and management library for Emacs.
#+END_QUOTE
http://batsov.com/projectile/


#+begin_src emacs-lisp
  (use-package projectile
    :ensure t
    :diminish projectile-mode
    :commands projectile-mode
    :config
    (progn
      (setq projectile-indexing-method 'alien
            projectile-remember-window-configs t
            projectile-switch-project-action 'projectile-dired
            projectile-completion-system 'default
            projectile-enable-caching nil
            compilation-read-command nil ; do not prompt for a compilation command
            )

      (projectile-global-mode)
      (setq projectile-completion-system 'helm)

      (use-package ag
        :commands ag
        :ensure t)))
#+end_src

** [[https://github.com/milkypostman/powerline][powerline]]

#+begin_src emacs-lisp
(use-package powerline
  :ensure t
  :config
  (progn
    (setq powerline-arrow-shape 'arrow14)
    (setq powerline-default-separator-dir '(right . left))

    (custom-set-faces
     '(mode-line ((t (:foreground "#030303" :background "#6b6b6b" :box nil))))
     '(mode-line-inactive ((t (:foreground "#f9f9f9" :background "#6b6b6b" :box nil)))))

    (setq powerline-color1 "#49483E")
    (setq powerline-color2 "#333333")
    (powerline-default-theme)
    ))
#+end_src

** [[https://melpa.org/#/python-mode][python-mode]]

Integrates with IPython.

#+begin_src emacs-lisp :tangle no
  (use-package python-mode
    :ensure t)
#+end_src

** [[https://github.com/emacsmirror/revive][revive]]

Using revive

- use ~M-x save-current-configuration~ to save window configuration.
- use ~M-x resume~ to load window configuration.

#+begin_src emacs-lisp
(use-package revive
  :ensure t)
#+end_src
** [[https://github.com/Fanael/rainbow-delimiters][rainbow-delimiters]]

Highlight brackets according to their depth

#+BEGIN_SRC emacs-lisp
(use-package rainbow-delimiters
  :ensure t)
#+END_SRC

** [[https://github.com/ieure/scratch-el][scratch]]

Convenient package to create =*scratch*= buffers that are based on the current buffer's major mode.
This is more convienent than manually creating a buffer to do some scratch work or reusing the
initial =*scratch*= buffer.

#+begin_src emacs-lisp
(use-package scratch
  :ensure t)
#+end_src

** [[https://github.com/wasamasa/shackle][shackle]]

Declarative popup window rules.

#+BEGIN_SRC emacs-lisp
(setq shackle-rules
      '((svg-2048-mode :same t)
        ("*Help*" :align t :ratio 0.4 :select t)
        ("\\`\\*helm.*?\\*\\'" :regexp t :align t :ratio 0.4)
        ((compilation-mode "\\`\\*firestarter\\*\\'"
          "\\`\\*magit-diff: .*?\\*\\'") :regexp t :noselect t)
        ((inferior-scheme-mode "*shell*" "*eshell*") :popup t))
       shackle-default-rule '(:select t)
       shackle-inhibit-window-quit-on-same-windows t)
#+END_SRC

** [[https://github.com/Fuco1/smartparens][smartparens]]

#+begin_src emacs-lisp
(use-package smartparens
  :ensure t
  :diminish smartparens-mode
  :config (progn (require 'smartparens-config)
                 (smartparens-global-mode t)))
#+end_src

*** Smartparens org mode

Set up some pairings for org mode markup. These pairings won't
activate by default; they'll only apply for wrapping regions.

#+begin_src emacs-lisp
(sp-local-pair 'org-mode "~" "~" :actions '(wrap))
(sp-local-pair 'org-mode "/" "/" :actions '(wrap))
(sp-local-pair 'org-mode "*" "*" :actions '(wrap))
#+end_src
** [[https://github.com/mickeynp/smart-scan][smart-scan]]

Quickly jumps between other symbols found at point in Emacs.
http://www.masteringemacs.org/article/smart-scan-jump-symbols-buffer

#+begin_src emacs-lisp
(use-package smartscan
  :ensure t
  :config (global-smartscan-mode 1))
#+end_src

** [[https://github.com/mrkkrp/vimish-fold][vimish-fold]]
#+BEGIN_SRC emacs-lisp
(use-package vimish-fold
  :ensure t
  :config (vimish-fold-global-mode 1)
  )
#+END_SRC
** [[https://github.com/benma/visual-regexp.el][visual-regexp]]

#+begin_src emacs-lisp
(use-package visual-regexp
  :ensure t
  :init
  (use-package visual-regexp-steroids :ensure t)
  :bind (("C-c r" . vr/replace)
         ("C-c q" . vr/query-replace)
         ("C-c m" . vr/mc-mark) ; Need multiple cursors
         ("C-M-r" . vr/isearch-backward)
         ("C-M-s" . vr/isearch-forward)))
#+end_src

** [[https://github.com/capitaomorte/yasnippet][yasnippet]]

It takes a few seconds to load and I don't need them immediately when
Emacs starts up, so we can defer loading yasnippet until there's some
idle time.

Large collection of snippets: [[https://github.com/AndreaCrotti/yasnippet-snippets][Andrea Crotti's collection]].

#+begin_src emacs-lisp
(use-package yasnippet
  :ensure t
  :diminish yas-minor-mode
  :config
  (setq yas-snippet-dirs (concat user-emacs-directory "snippets"))
  (yas-global-mode))
#+end_src

** [[https://github.com/fxbois/web-mode][web-mode]]

#+begin_src emacs-lisp :tangle no
(use-package web-mode
  :ensure t)
#+end_src

** [[https://github.com/purcell/whole-line-or-region][whole-line-or-region]]

#+begin_src emacs-lisp
(use-package whole-line-or-region
  :ensure t
  :diminish whole-line-or-region-mode
  :config (whole-line-or-region-mode t))
#+end_src

* Computer-specific settings

Load some computer-specific settings, such as the name and and email address. The way the settings
are loaded is based off of [[https://github.com/magnars/.emacs.d][Magnar Sveen's]] config.

#+begin_src emacs-lisp
(defvar nl/user-settings-dir nil
  "The directory with user-specific Emacs settings for this
  user.")

;; Settings for currently logged in user
(require 's)
(setq nl/user-settings-dir
      (concat user-emacs-directory
              "users/"
              (s-trim (shell-command-to-string "hostname -s"))))
(add-to-list 'load-path nl/user-settings-dir)

;; Load settings specific for the current user
(when (file-exists-p nl/user-settings-dir)
  (mapc 'load (directory-files nl/user-settings-dir nil "^[^#].*el$")))
#+end_src

* Languages

Programming mode hook.

#+begin_src emacs-lisp
(add-hook 'prog-mode-hook 'subword-mode)

(defun my-common-prog-mode-settings ()
  "Enables settings common between programming language modes."
  (progn
    ;
    ; Set tab and CR/LF keys to call their corresponding more-general
    ; functions.  This needs to be here to override the settings of some modes
    ; (e.g. c++-mode changes the tab key to do a re-indent).
    ;
    (local-set-key "\t" 'tab-to-tab-stop)
    (local-set-key "\n" 'newline-and-indent)
    (local-set-key "\r" 'newline-and-indent)
    ;
    ; Set paragraph/comment auto-formatting to wrap at column 100.
    ;
    (set-fill-column 100)
    ;
    ; Set the comment column to zero so that lisp comment lines will act like
    ; C++ comments (i.e. line up with the code), and not automatically indent
    ; to column 50.
    ;
    (setq comment-column 0)
    (rainbow-delimiters-mode) ;; See unbalanced parens
    (push '(">=" . ?≥) prettify-symbols-alist)
    (push '("<=" . ?≤) prettify-symbols-alist)
    (push '("->" . ?→) prettify-symbols-alist)
    ))

(setq makefile-mode-hook 'my-common-prog-mode-settings)
(setq sh-mode-hook       'my-common-prog-mode-settings)
#+end_src

** C

#+begin_src emacs-lisp
(defconst nelson-c-style
  '((c-tab-always-indent . t)
    (c-set-style "K&R")
    (c-basic-offset . 3)
    (c-offsets-alist . ((statement-block-intro . +)
                        (substatement-open     . 0)
                        (label                 . 0)
                        (case-label            . +)
                        (statement-cont        . +)
                        )))
  "Nelson programming style.")

;; Customizations for all of c-mode, c++-mode, and objc-mode
(defun my-c-mode-common-hook ()
  ;; add my personal style and set it for the current buffer
  (c-add-style "NELSON" nelson-c-style t)
  ;; offset customizations not in nelson-c-style
  (c-set-offset 'member-init-intro '++)
  ;; other customizations
  ;(c-toggle-auto-state 1) ;; Turn on auto newline
  (my-common-prog-mode-settings)
  ; makes the underscore part of a word in C and C++ modes
  (modify-syntax-entry ?_ "w" c++-mode-syntax-table)
  (modify-syntax-entry ?_ "w" c-mode-syntax-table)
  (lambda ()
    (when (derived-mode-p 'c-mode 'c++-mode 'java-mode)
      (ggtags-mode 1)))
  )

(add-hook 'c-mode-common-hook 'my-c-mode-common-hook)
#+end_src

** Emacs lisp

#+BEGIN_SRC emacs-lisp
(setq emacs-lisp-mode-hook 'my-common-prog-mode-settings)
#+END_SRC

** Java

#+begin_src emacs-lisp
(defun my-java-mode-hook ()
  (setq c-basic-offset 4
        tab-width 4
        indent-tabs-mode nil)
  )


(add-hook 'java-mode-hook 'my-java-mode-hook)
#+END_SRC

Utillity function to restart the Eclim server.

#+BEGIN_SRC emacs-lisp
(defun nl/restart-eclim (workspace-dir)
  "Restarts eclim.  If it is currently active then it is stopped first."
  (interactive (list (read-directory-name "Workspace directory: "
                                          eclimd-default-workspace nil t)))
  (if (get-buffer "*eclimd*") (stop-eclimd))
  (start-eclimd workspace-dir)
  (switch-to-buffer "*eclimd*")
  )
#+end_src

** Perl

#+begin_src emacs-lisp
(defun my-cperl-setup ()
  (cperl-set-style "C++")
  (my-common-prog-mode-settings))

(add-hook 'cperl-mode-hook 'my-cperl-setup)
#+end_src

** SQL

Taken from:
- http://truongtx.me/2014/08/23/setup-emacs-as-an-sql-database-client/

#+BEGIN_SRC emacs-lisp
(require 'epa-file)
(epa-file-enable)

(setq sql-connection-alist
      '((che.dev (sql-product 'mysql)
                 (sql-port 3306)
                 (sql-server "localhost")
                 (sql-user "root")
                 (sql-database "mysql"))
        (obelix.dev (sql-product 'mysql)
                    (sql-port 3306)
                    (sql-server "localhost")
                    (sql-user "root")
                    (sql-database "mysql"))))

(defun nl/sql-connect (product connection)
  "Connects to a database server of type PRODUCT using the CONNECTION type."
  (require 'nl-passwords (concat user-emacs-directory "my-password.el.gpg"))

  ;; update the password to the sql-connection-alist
  (let ((connection-info (assoc connection sql-connection-alist))
        (sql-password (car (last (assoc connection nl-sql-passwords)))))
    (delete sql-password connection-info)
    (nconc connection-info `((sql-password ,sql-password)))
    (setq sql-connection-alist (assq-delete-all connection sql-connection-alist))
    (add-to-list 'sql-connection-alist connection-info))

  ;; connect to database
  (setq sql-product product)
  (if current-prefix-arg
      (sql-connect connection connection)
    (sql-connect connection)))

(defun nl/sql-che-dev ()
  "Connects to the MySQL server running on machine 'che'."
  (nl/sql-connect 'mysql 'che.dev))

(defun nl/sql-obelix-dev ()
  "Connects to the MySQL server running on machine 'obelix'."
  (nl/sql-connect 'mysql 'obelix.dev))

(defvar nl/sql-servers-list
  '(("Che Dev" nl/sql-che-dev)
    ("Obelix Dev" nl/sql-obelix-dev))
  "A list of server name and the function to connect.")

(defun nl/sql-connect-server (func)
  "Connect to the input server using nl/sql-servers-list and FUNC."
  (interactive
   (helm-comp-read "Select server: " nl/sql-servers-list))
  (funcall func))
#+END_SRC
* Misc
** Aligning things

Borrowed from:

http://danconnor.com/post/5028ac91e8891a000000111f/align_and_columnize_key_value_data_in_emacs

#+BEGIN_SRC emacs-lisp
(defun align-colons (beg end)
  (interactive "r")
  (align-regexp beg end ":\\(\\s-*\\)" 1 1 t))

(defun align-commas (beg end)
  (interactive "r")
  (align-regexp beg end ",\\(\\s-*\\)" 1 1 t))

(defun align-equals (beg end)
  (interactive "r")
  (align-regexp beg end "\\(\\s-*\\)=" 1 1 t))
#+END_SRC
** Font size

=C-c C-+= and =C-c C--= are pretty useful, but only resize the current
buffer.  Here's a hack using ~set-frame-font~ and altering the font
size only:

#+BEGIN_SRC emacs-lisp
(defun my-alter-frame-font-size (fn)
  (let* ((current-font-name (frame-parameter nil 'font))
         (decomposed-font-name (x-decompose-font-name current-font-name))
         (font-size (string-to-int (aref decomposed-font-name 5))))
    (aset decomposed-font-name 5 (int-to-string (funcall fn font-size)))
    (set-frame-font (x-compose-font-name decomposed-font-name))))

(defun my-inc-frame-font-size ()
  (interactive)
  (my-alter-frame-font-size '1+))

(defun my-dec-frame-font-size ()
  (interactive)
  (my-alter-frame-font-size '1-))

(global-set-key (kbd "C-+") 'my-inc-frame-font-size)
(global-set-key (kbd "C--") 'my-dec-frame-font-size)
#+END_SRC

** Journal

#+BEGIN_SRC emacs-lisp
(defconst nl/tl_dts-format-string "%e %b %Y %H:%M:%S"
  "A string specifying the format of the date-time stamp.
Refer to the documentation for 'format-time-string' for an explanation of the
meta characters available for use in this string.  Non-meta characters will
be inserted into the buffer without interpretation.")

;; Function: insert-dts
;;   Insert the date and time into the current buffer at the current location.
;;
(defun nl/insert-dts ()
  "Insert the date and time into the current buffer at the current location.
See the documentation for nl/tl_dts-format-string to change the format of the
date-time stamp."
  (interactive)
  (insert (format-time-string nl/tl_dts-format-string (current-time))))

(defvar nl/tl_ds-format-string "%b%e/%Y"
  "A string specifying the format of the date stamp.
Refer to the documentation for 'format-time-string' for an explanation of the
meta characters available for use in this string.  Non-meta characters will
be inserted into the buffer without interpretation.")

;; Function: insert-ds
;;   Insert the date into the current buffer at the current location.
;;
(defun nl/insert-ds ()
  "Insert the date into the current buffer at the current location.
See the documentation for nl/tl_dts-format-string to change the format of the
date-time stamp."
  (interactive)
  (insert (format-time-string nl/tl_ds-format-string (current-time))))

 (defun nl/journal ()
  "Add an entry in the journal file."
  (interactive)
  (find-file "~/Dropbox/journal.org")
  (end-of-buffer)
  (insert "\n\n")
  (insert "* ")
  (nl/insert-dts)
  (insert "\n")
  )
#+END_SRC
